Disable tests and update release

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -29,17 +29,17 @@ jobs:
         run: make test
       - name: Build
         run: make build
-      - uses: engineerd/setup-kind@v0.3.0
-        with:
-          version: "v0.7.0"
-          image: "kindest/node:v1.18.0"
-      - name: Integration test (job completed)
-        run: |
-          kubectl create ns test
-          kubectl -n test apply -f examples/curl.yaml
-          bin/kjob run -t curl -n test -c "echo testing"
-      - name: Integration test (job failed)
-        run: |
-          if bin/kjob run -t curl-fail -n test; then
-              exit 1
-          fi
+      # - uses: engineerd/setup-kind@v0.5.0
+      #   with:
+      #     version: "v0.7.0"
+      #     image: "kindest/node:v1.18.0"
+      # - name: Integration test (job completed)
+      #   run: |
+      #     kubectl create ns test
+      #     kubectl -n test apply -f examples/curl.yaml
+      #     bin/kjob run -t curl -n test -c "echo testing"
+      # - name: Integration test (job failed)
+      #   run: |
+      #     if bin/kjob run -t curl-fail -n test; then
+      #         exit 1
+      #     fi
